OpenNebula/addon-storpool

- misc/integration-test.sh
A simple integration test to see if the integration behaves properly.
Does the following:
* instantiate a vm
* live migrate the vm
* non-live migrate the vm
* create a disk
* attach and detach disk
> integration-test: initial import

- addon-storpoolrc
- datastore/storpool/clone
- datastore/storpool/cp
- datastore/storpool/mkfs
- datastore/storpool/monitor
- datastore/storpool/monitor_helper-sync
- datastore/storpool/rm
- datastore/storpool/snap_flatten
- datastore/storpool/snap_revert
- docs/advanced_configuration.md
- misc/spMigrateContext.sh
- tm/storpool/context
- tm/storpool/cpds
- tm/storpool/delete
- tm/storpool/failmigrate
- tm/storpool/mkimage
- tm/storpool/monitor
- tm/storpool/monitor_disk
- tm/storpool/monitor_ds
- tm/storpool/mv
- tm/storpool/postmigrate
- tm/storpool/premigrate
- tm/storpool/storpool_common.sh
- vmm/kvm/restore.storpool
- vmm/kvm/restore.storpool-post
- vmm/kvm/save.storpool
- vmm/kvm/save.storpool-pre
currently used to bring a testing ONE in parallel to the production one.
Note: Needs separated HV hosts though.
> multiverse - support multiple OpenNebulas on a cluster

- vmm/kvm/vmTweakHypervEnlightenments.py
> vmTweakHypervEnlightenments.py: look all controllers

- vmm/kvm/vmTweakHypervEnlightenments.py
to enable ioeventfd for virtio-scsi-pci
> vmTweakHypervEnlightenments add --ioeventfd

- addon-storpoolrc
- datastore/storpool/monitor
- tm/storpool/monitor
- tm/storpool/mv
- tm/storpool/mvds
- tm/storpool/storpool_common.sh
clarify a comment
add short description for the default and tunning variables
remove obsolete function/feature
> Refactor 20180322

- docs/advanced_configuration.md
- vmm/kvm/deploy-tweaks
- vmm/kvm/deploy-tweaks.d.example/cpu.py
to work with (optional) default values set in the `kvmrc` file.
update docs.
Signed-off-by: Anton Todorov <atodorov-storpool@users.noreply.github.com>
> improve deploy-tweaks

- vmm/kvm/deploy-tweaks.d.example/vfhostdev2interface.py
> use the MAC provided by OpenNebula

- hooks/net_fw_hook
where FILTER_IP_SPOOFING=YES
Signed-off-by: Anton Todorov <atodorov-storpool@users.noreply.github.com>
> handle alias IP for all VN_MADs

- datastore/storpool/rm
- tm/storpool/delete
- tm/storpool/storpool_common.sh
Signed-off-by: Anton Todorov <atodorov-storpool@users.noreply.github.com>
> remote volume backup on delete

- hooks/net_fw_hook
also fixed example hook config
> Added IPv6 SLAAC support

- datastore/storpool/monitor_helper-sync
- tm/storpool/storpool_common.sh
> Fix Template propagate

- hooks/volumecare/vc-policy.sh
- hooks/volumecare/volumecare
- misc/volumecare.hook
- tm/storpool/clone
- tm/storpool/delete
- tm/storpool/ln
- tm/storpool/mkimage
- tm/storpool/mvds
- tm/storpool/storpool_common.sh
Set StorPool Volumecate tag for VM using a USER TEMPLATE variable named  _VC_POLICY_
> Volumecare

- tm/storpool/context
- tm/storpool/storpool_common.sh
when starting a contextualizing a VM
> force-detach volumes from other hosts

- tm/storpool/snap_revert
- vmm/kvm/snapshot_revert-storpool
> set VC policy tag on disk/VM snapshot revert

- tm/storpool/failmigrate
- tm/storpool/postmigrate
- tm/storpool/premigrate
- tm/storpool/storpool_common.sh
> rework volume attach in {pre,post,fail}migrate

- docs/resizeCpuMem.md
- hooks/resizeCpuMem.sh
- misc/resizeCpuMem.hook
- vmm/kvm/deploy-tweaks.d.example/resizeCpuMem.py
> add domain-tweak to basic live CPU and MEM resize

- docs/naming_convention.md
- docs/uefi_secure_boot.md
- tm/storpool/context
- tm/storpool/delete
- tm/storpool/failmigrate
- tm/storpool/mv
- tm/storpool/postmigrate
- tm/storpool/premigrate
- tm/storpool/storpool_common.sh
- vmm/kvm/deploy-tweaks.d.example/os.py
for UEFI boot (SecureBoot compatible too)
> Nvram support

- datastore/storpool/export
- datastore/storpool/export.delete
> export to marketplace for opennebula 6.0+

- datastore/storpool/mkfs
- tm/storpool/mkimage
> mk/fs/image: fix backward compatibility

- tm/storpool/cpds
- tm/storpool/storpool_common.sh
Disabled by default.
To enable set in addon-storpoolrc:
DISK_SAVEAS_FSFREEZE=1
> cpds: make domfsfreeze/thaw optional

- scripts/install-6.2.sh
> enable opennebula-6.2

- install.sh
- scripts/install-6.4.sh
to avoid confusing onecfg
Change-Id: Id50132bec3b098a3b83436a2a28554672ab77763
> install: do not use symlinks

- README.md
- docs/known_issues.md
Change-Id: I495141c790fb3d0e24f9759b7b9bdd0bd0f2c570
> add docs/known_issues.md

- vmm/kvm/deploy-tweaks.d.example/disk-serial.py
By default the generated Disk Serial number is persistent for the peristent images.
Works for 'DISK' block devices only. The CDROM devices are excluded.
There is a fall-back to the initial implementation by defining T_DISKSERIAL=HASHPATH in the addon-storpoolrc or the VM attributes
Change-Id: I7faca00bf79c6f1fc811507f2642ddf3f2c73410
> deploy-tweaks: refactor disk-serial.py

- tm/storpool/delete
and the possible storage driver hint (*.monitor)
Change-Id: I14babf4f5330b291fe2d9ff19d36b14c0f416d46
> fix tm/delete to delete only the desired disk

- datastore/storpool/monitor_helper-sync
Change-Id: I4b20986af7cfea37d062143835c3b797bbf37b04
> grrrr fix rebase/merge regression

- tm/storpool/context
Change-Id: I5fa91e3d0f30cea73ee3c9313024df6c265898cc
> fix alternate UEFI vars handling
